### ISSUE TITLE
When validating and cleaning, subsequent artboards move into main artboards.

### ISSUE THREAD

**Issue by antmoritz** [monzo/file-cleaner#4]
There seems to be a bug when validating and cleaning and the page contains subsequent artboards (101, 201, etc) to the side of main artboards (100, 200, etc.).

When I validate and clean, the subsequent artboards move into the position where the main artboards are. Then I have to manually move them out of there. See attached pictures.

<img width="1792" alt="screenshot 2018-12-16 at 14 20 07" src="https://user-images.githubusercontent.com/1520453/50054061-3462c880-013e-11e9-9ce1-6706c1191a25.png">
<img width="1792" alt="screenshot 2018-12-16 at 14 20 15" src="https://user-images.githubusercontent.com/1520453/50054062-3462c880-013e-11e9-86d5-922812c35234.png">

Running Sketch 52.5 on MacBook Pro with macOS Mojave 10.14.

**Comment by zancler** [comment]
Thanks so much for flagging, we're looking at this currently and will aim to get a fix out this week.

The reason for this is that it is built for mobile use (as that was our only use case), and therefore automatically goes to every 500px on the X axis. Fix coming soon!

**Comment by antmoritz** [comment]
Ah - that makes sense. 

Looking forward to the update, then.

**Comment by spectrl** [comment]
This should be fixed now!
